### ISSUE TITLE
Translate API error handler

### ISSUE THREAD

**Issue by Seakimhour** [Seakimhour/pro-translate#44]
when select "&バース両氏" an error occurred.

```js
TranslatePanel.vue:80 Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')
    at Proxy.translate (TranslatePanel.vue:80:40)
    at async Proxy.initialize (TranslatePanel.vue:57:7)
```

```js
    async translate() {
      this.targetLanguage = this.settings.targetLanguage.code;

      const detectedLanguage = await detectLanguage(this.selectedText);

      this.sourceLanguage = detectedLanguage.languages[0].language;

      const matchTargetLanguage = this.sourceLanguage === this.targetLanguage;

      if (matchTargetLanguage && this.settings.autoSwitch)
        this.targetLanguage = this.settings.secondTargetLanguage.code;

      const response = await translateAPI(
        this.selectedText,
        this.sourceLanguage,
        this.targetLanguage
      );

      this.translatedText = response[0][0][0];    // ERROR HERE
    },
```

**Comment by Seakimhour** [comment]
Done
- #46
